[tool.poetry]
name = "monitor-gastos-api"
version = "0.1.0"
description = ""
authors = ["User"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
uvicorn = {extras = ["standard"], version = "*"}
sqlalchemy = "*"
psycopg2-binary = "*"
python-dotenv = "*"
bcrypt = "*"
python-jose = {extras = ["cryptography"], version = "*"}
python-multipart = "*"
email-validator = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
